# Generated by Django 5.2 on 2025-06-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='stocks_stoc_stock_i_9494c7_idx')],
            },
        ),
    ]
