services:
  - type: web
    name: stock-backend
    env: docker
    plan: free
    dockerContext: ./backend           
    dockerfilePath: Dockerfile             
    envVars:
      - key: DJANGO_SECRET_KEY
        fromDatabase: true
      - key: DB_NAME
        fromDatabase: true
      - key: DB_USER
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true
      - key: DB_HOST
        fromDatabase: true
      - key: DB_PORT
        fromDatabase: true
